name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/data_preprocessing/loan_approval_dataset_preprocessing.csv"
  MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
  MLFLOW_ARTIFACT_URI: "${{ github.workspace }}/mlruns"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python 3.13.7
      - name: Set up Python 3.13.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.7"

      # 3. Check Env Variables
      - name: Check Env
        run: |
          echo "CSV_URL=$CSV_URL"
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
          echo "MLFLOW_ARTIFACT_URI=$MLFLOW_ARTIFACT_URI"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow imbalanced-learn scikit-learn pandas numpy

      # 5. Run MLflow Project
      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      # 6. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "loan"

      # 8. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 9. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag loan ${{ secrets.DOCKER_HUB_USERNAME }}/loan:latest

      # 10. Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/loan:latest

      # 11. Save mlruns to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add mlruns/ || true
          git commit -m "Save mlruns from CI/CD run" || true
          git push origin main || true
